name: Python application

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.6
      uses: actions/setup-python@v1
      with:
        python-version: 3.6
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pipenv
        
    - name: Set-up env with pipenv
      run: |
        pipenv install --ignore-pipfile

    - name: Test with pytest
      run: |
        pip install pytest
        pytest data_to_tfrecords/test/test_utils.py
        
    - name: Run main file
      run: |
        python -m data_to_tfrecords.main
  
